export interface Disease {
  id: string;
  name: string;
  category: string;
  overview: string;
  symptoms: string[];
  causes: string[];
  treatments: string[];
}

export const diseases: Disease[] = [
  {
    id: '1',
    name: 'Type 2 Diabetes',
    category: 'Metabolic',
    overview: 'A chronic condition affecting how the body processes blood sugar (glucose).',
    symptoms: ['Increased thirst', 'Frequent urination', 'Unexplained weight loss', 'Fatigue', 'Blurred vision'],
    causes: ['Insulin resistance', 'Genetics', 'Obesity', 'Sedentary lifestyle'],
    treatments: ['Lifestyle changes', 'Metformin medication', 'Insulin therapy', 'Regular exercise', 'Healthy diet'],
  },
  {
    id: '2',
    name: 'Hypertension',
    category: 'Cardiovascular',
    overview: 'High blood pressure, a condition where blood pressure in arteries is persistently elevated.',
    symptoms: ['Headaches', 'Shortness of breath', 'Nosebleeds', 'Chest pain', 'Dizziness'],
    causes: ['Genetics', 'High sodium intake', 'Stress', 'Obesity', 'Lack of exercise'],
    treatments: ['ACE inhibitors', 'Beta-blockers', 'Low-sodium diet', 'Regular exercise', 'Stress management'],
  },
  {
    id: '3',
    name: 'Asthma',
    category: 'Respiratory',
    overview: 'A chronic respiratory condition causing inflammation and narrowing of airways.',
    symptoms: ['Wheezing', 'Shortness of breath', 'Chest tightness', 'Coughing', 'Rapid breathing'],
    causes: ['Allergens', 'Air pollution', 'Cold air', 'Exercise', 'Respiratory infections'],
    treatments: ['Bronchodilators', 'Corticosteroid inhalers', 'Avoid triggers', 'Allergy medications'],
  },
  {
    id: '4',
    name: 'Depression',
    category: 'Mental Health',
    overview: 'A mood disorder causing persistent feelings of sadness and loss of interest.',
    symptoms: ['Persistent sadness', 'Loss of interest', 'Sleep changes', 'Fatigue', 'Difficulty concentrating'],
    causes: ['Genetics', 'Brain chemistry', 'Trauma', 'Chronic stress', 'Major life changes'],
    treatments: ['Cognitive therapy', 'Antidepressants', 'Exercise', 'Support groups', 'Lifestyle changes'],
  },
  {
    id: '5',
    name: 'Osteoarthritis',
    category: 'Musculoskeletal',
    overview: 'A degenerative joint disease causing cartilage breakdown and joint pain.',
    symptoms: ['Joint pain', 'Stiffness', 'Reduced flexibility', 'Swelling', 'Bone spurs'],
    causes: ['Age', 'Joint injury', 'Obesity', 'Genetics', 'Repetitive stress'],
    treatments: ['Pain relievers', 'Physical therapy', 'Weight management', 'Joint replacement', 'Exercise'],
  },
  {
    id: '6',
    name: 'Migraine',
    category: 'Neurological',
    overview: 'A neurological condition characterized by intense, debilitating headaches.',
    symptoms: ['Severe headache', 'Nausea', 'Light sensitivity', 'Visual disturbances', 'Vomiting'],
    causes: ['Genetics', 'Hormonal changes', 'Stress', 'Certain foods', 'Sleep changes'],
    treatments: ['Triptans', 'Pain relievers', 'Preventive medications', 'Lifestyle modifications', 'Stress management'],
  },
  {
    id: '7',
    name: 'GERD',
    category: 'Digestive',
    overview: 'Gastroesophageal reflux disease causes stomach acid to flow back into the esophagus.',
    symptoms: ['Heartburn', 'Regurgitation', 'Difficulty swallowing', 'Chest pain', 'Chronic cough'],
    causes: ['Weak lower esophageal sphincter', 'Obesity', 'Pregnancy', 'Hiatal hernia', 'Certain foods'],
    treatments: ['Proton pump inhibitors', 'H2 blockers', 'Lifestyle changes', 'Weight loss', 'Avoid trigger foods'],
  },
  {
    id: '8',
    name: 'Anxiety Disorder',
    category: 'Mental Health',
    overview: 'Excessive worry and fear that interferes with daily activities.',
    symptoms: ['Excessive worry', 'Restlessness', 'Difficulty concentrating', 'Muscle tension', 'Sleep problems'],
    causes: ['Genetics', 'Brain chemistry', 'Trauma', 'Stress', 'Environmental factors'],
    treatments: ['Cognitive behavioral therapy', 'Anti-anxiety medications', 'Relaxation techniques', 'Exercise'],
  },
  {
    id: '9',
    name: 'Rheumatoid Arthritis',
    category: 'Autoimmune',
    overview: 'An autoimmune disorder causing chronic inflammation of joints.',
    symptoms: ['Joint swelling', 'Morning stiffness', 'Fatigue', 'Fever', 'Weight loss'],
    causes: ['Autoimmune response', 'Genetics', 'Smoking', 'Environmental factors'],
    treatments: ['DMARDs', 'Biologics', 'Corticosteroids', 'Physical therapy', 'Joint protection'],
  },
  {
    id: '10',
    name: 'Chronic Kidney Disease',
    category: 'Renal',
    overview: 'Progressive loss of kidney function over time.',
    symptoms: ['Fatigue', 'Swelling', 'Changes in urination', 'Nausea', 'Shortness of breath'],
    causes: ['Diabetes', 'Hypertension', 'Glomerulonephritis', 'Polycystic kidney disease'],
    treatments: ['Blood pressure control', 'Diabetes management', 'Low-protein diet', 'Dialysis', 'Kidney transplant'],
  },
  {
    id: '11',
    name: 'Hypothyroidism',
    category: 'Endocrine',
    overview: 'Underactive thyroid gland not producing enough thyroid hormone.',
    symptoms: ['Fatigue', 'Weight gain', 'Cold sensitivity', 'Constipation', 'Dry skin'],
    causes: ['Autoimmune disease', 'Thyroid surgery', 'Radiation therapy', 'Medications'],
    treatments: ['Levothyroxine', 'Regular monitoring', 'Lifestyle modifications'],
  },
  {
    id: '12',
    name: 'COPD',
    category: 'Respiratory',
    overview: 'Chronic obstructive pulmonary disease causing blocked airflow and breathing difficulties.',
    symptoms: ['Chronic cough', 'Shortness of breath', 'Wheezing', 'Chest tightness', 'Frequent infections'],
    causes: ['Smoking', 'Air pollution', 'Occupational dust', 'Genetics'],
    treatments: ['Bronchodilators', 'Steroids', 'Oxygen therapy', 'Pulmonary rehabilitation', 'Smoking cessation'],
  },
  {
    id: '13',
    name: 'Psoriasis',
    category: 'Dermatological',
    overview: 'A chronic autoimmune condition causing rapid skin cell buildup.',
    symptoms: ['Red patches', 'Silvery scales', 'Dry cracked skin', 'Itching', 'Burning sensation'],
    causes: ['Immune system', 'Genetics', 'Stress', 'Infections', 'Cold weather'],
    treatments: ['Topical corticosteroids', 'Vitamin D analogues', 'Phototherapy', 'Biologics'],
  },
  {
    id: '14',
    name: 'Celiac Disease',
    category: 'Digestive',
    overview: 'An autoimmune disorder triggered by consuming gluten.',
    symptoms: ['Diarrhea', 'Abdominal pain', 'Bloating', 'Fatigue', 'Weight loss'],
    causes: ['Genetics', 'Gluten consumption', 'Autoimmune response'],
    treatments: ['Gluten-free diet', 'Nutritional supplements', 'Symptom management'],
  },
  {
    id: '15',
    name: 'Fibromyalgia',
    category: 'Musculoskeletal',
    overview: 'A disorder causing widespread musculoskeletal pain.',
    symptoms: ['Widespread pain', 'Fatigue', 'Sleep problems', 'Cognitive difficulties', 'Mood changes'],
    causes: ['Genetics', 'Infections', 'Physical trauma', 'Psychological stress'],
    treatments: ['Pain relievers', 'Antidepressants', 'Physical therapy', 'Stress management', 'Exercise'],
  },
  {
    id: '16',
    name: 'Sleep Apnea',
    category: 'Sleep Disorder',
    overview: 'A serious sleep disorder where breathing repeatedly stops and starts.',
    symptoms: ['Loud snoring', 'Gasping for air', 'Morning headache', 'Daytime sleepiness', 'Difficulty concentrating'],
    causes: ['Obesity', 'Neck circumference', 'Narrow airway', 'Age', 'Family history'],
    treatments: ['CPAP therapy', 'Oral appliances', 'Weight loss', 'Positional therapy', 'Surgery'],
  },
  {
    id: '17',
    name: "Crohn's Disease",
    category: 'Digestive',
    overview: 'A chronic inflammatory bowel disease affecting the digestive tract.',
    symptoms: ['Abdominal pain', 'Diarrhea', 'Weight loss', 'Fatigue', 'Mouth sores'],
    causes: ['Immune system', 'Genetics', 'Environmental factors', 'Smoking'],
    treatments: ['Anti-inflammatory drugs', 'Immunosuppressants', 'Biologics', 'Surgery', 'Dietary changes'],
  },
  {
    id: '18',
    name: 'Lupus',
    category: 'Autoimmune',
    overview: 'A systemic autoimmune disease affecting multiple organs.',
    symptoms: ['Butterfly rash', 'Fatigue', 'Joint pain', 'Fever', 'Photosensitivity'],
    causes: ['Genetics', 'Environmental triggers', 'Hormones', 'Infections'],
    treatments: ['NSAIDs', 'Antimalarials', 'Corticosteroids', 'Immunosuppressants'],
  },
  {
    id: '19',
    name: 'Eczema',
    category: 'Dermatological',
    overview: 'A condition causing inflamed, itchy, and red skin.',
    symptoms: ['Dry skin', 'Itching', 'Red patches', 'Cracked skin', 'Oozing lesions'],
    causes: ['Genetics', 'Immune system', 'Environmental triggers', 'Allergens'],
    treatments: ['Moisturizers', 'Topical corticosteroids', 'Antihistamines', 'Avoiding triggers'],
  },
  {
    id: '20',
    name: 'Multiple Sclerosis',
    category: 'Neurological',
    overview: 'An autoimmune disease affecting the central nervous system.',
    symptoms: ['Numbness', 'Weakness', 'Vision problems', 'Balance issues', 'Fatigue'],
    causes: ['Immune system', 'Genetics', 'Environmental factors', 'Vitamin D deficiency'],
    treatments: ['Disease-modifying therapies', 'Corticosteroids', 'Physical therapy', 'Symptom management'],
  },
  {
    id: '21',
    name: "Parkinson's Disease",
    category: 'Neurological',
    overview: 'A progressive nervous system disorder affecting movement.',
    symptoms: ['Tremor', 'Slowed movement', 'Rigid muscles', 'Balance problems', 'Changes in speech'],
    causes: ['Genetics', 'Environmental factors', 'Age', 'Gender'],
    treatments: ['Levodopa', 'Dopamine agonists', 'Physical therapy', 'Deep brain stimulation'],
  },
  {
    id: '22',
    name: 'Anemia',
    category: 'Hematological',
    overview: 'A condition where blood lacks adequate healthy red blood cells.',
    symptoms: ['Fatigue', 'Weakness', 'Pale skin', 'Shortness of breath', 'Dizziness'],
    causes: ['Iron deficiency', 'Vitamin deficiency', 'Chronic disease', 'Blood loss'],
    treatments: ['Iron supplements', 'Vitamin B12 injections', 'Dietary changes', 'Treating underlying cause'],
  },
  {
    id: '23',
    name: 'Gout',
    category: 'Musculoskeletal',
    overview: 'A form of arthritis characterized by sudden, severe attacks of joint pain.',
    symptoms: ['Intense joint pain', 'Swelling', 'Redness', 'Limited range of motion'],
    causes: ['High uric acid', 'Diet', 'Obesity', 'Genetics', 'Certain medications'],
    treatments: ['NSAIDs', 'Colchicine', 'Corticosteroids', 'Dietary changes', 'Uric acid-lowering medications'],
  },
  {
    id: '24',
    name: 'Hepatitis C',
    category: 'Infectious',
    overview: 'A viral infection causing liver inflammation.',
    symptoms: ['Fatigue', 'Nausea', 'Abdominal pain', 'Dark urine', 'Jaundice'],
    causes: ['Blood-to-blood contact', 'Sharing needles', 'Unsafe medical practices'],
    treatments: ['Antiviral medications', 'Lifestyle modifications', 'Regular monitoring', 'Liver transplant'],
  },
  {
    id: '25',
    name: 'Endometriosis',
    category: "Women's Health",
    overview: 'A disorder where tissue similar to uterine lining grows outside the uterus.',
    symptoms: ['Pelvic pain', 'Painful periods', 'Pain during intercourse', 'Infertility', 'Heavy menstrual bleeding'],
    causes: ['Retrograde menstruation', 'Genetics', 'Immune system', 'Hormones'],
    treatments: ['Pain medications', 'Hormone therapy', 'Surgery', 'Fertility treatment'],
  },
  {
    id: '26',
    name: 'Cataracts',
    category: 'Ophthalmological',
    overview: 'Clouding of the eye lens affecting vision.',
    symptoms: ['Blurred vision', 'Faded colors', 'Glare sensitivity', 'Halos around lights', 'Double vision'],
    causes: ['Aging', 'Diabetes', 'Smoking', 'Prolonged sun exposure', 'Eye injury'],
    treatments: ['Prescription glasses', 'Brighter lighting', 'Cataract surgery'],
  },
  {
    id: '27',
    name: 'Irritable Bowel Syndrome',
    category: 'Digestive',
    overview: 'A common disorder affecting the large intestine.',
    symptoms: ['Abdominal pain', 'Bloating', 'Gas', 'Diarrhea or constipation', 'Mucus in stool'],
    causes: ['Abnormal gut contractions', 'Nervous system', 'Gut inflammation', 'Infections', 'Gut bacteria changes'],
    treatments: ['Dietary changes', 'Fiber supplements', 'Anti-diarrheal medications', 'Stress management'],
  },
  {
    id: '28',
    name: 'Peripheral Artery Disease',
    category: 'Cardiovascular',
    overview: 'Narrowed arteries reducing blood flow to limbs.',
    symptoms: ['Leg pain when walking', 'Numbness', 'Coldness in lower leg', 'Slow-healing sores', 'Color changes'],
    causes: ['Atherosclerosis', 'Smoking', 'Diabetes', 'High blood pressure', 'High cholesterol'],
    treatments: ['Exercise programs', 'Medications', 'Angioplasty', 'Bypass surgery', 'Lifestyle changes'],
  },
  {
    id: '29',
    name: 'Allergic Rhinitis',
    category: 'Allergic',
    overview: 'Inflammation of nasal passages due to allergens.',
    symptoms: ['Sneezing', 'Runny nose', 'Itchy eyes', 'Congestion', 'Postnasal drip'],
    causes: ['Pollen', 'Dust mites', 'Pet dander', 'Mold', 'Cockroaches'],
    treatments: ['Antihistamines', 'Nasal corticosteroids', 'Decongestants', 'Immunotherapy', 'Avoiding allergens'],
  },
  {
    id: '30',
    name: 'Vertigo',
    category: 'Neurological',
    overview: 'A sensation of spinning or loss of balance.',
    symptoms: ['Spinning sensation', 'Balance problems', 'Nausea', 'Vomiting', 'Sweating'],
    causes: ['Inner ear problems', 'Head injury', 'Migraines', 'Medications', 'Stroke'],
    treatments: ['Vestibular rehabilitation', 'Medications', 'Canalith repositioning', 'Treating underlying cause'],
  },
    {
    id: '31',
    name: 'Alzheimer\'s Disease',
    category: 'Neurological',
    overview: 'A progressive brain disorder that affects memory, thinking and behavior.',
    symptoms: ['Memory loss', 'Difficulty with familiar tasks', 'Disorientation', 'Language problems', 'Poor judgment'],
    causes: ['Age', 'Genetics', 'Lifestyle factors', 'Head trauma', 'Cardiovascular health'],
    treatments: ['Cholinesterase inhibitors', 'Memantine', 'Cognitive stimulation', 'Occupational therapy', 'Support groups'],
  },
  {
    id: '32',
    name: 'Stroke',
    category: 'Cardiovascular',
    overview: 'Occurs when blood flow to an area of brain is cut off, causing brain cells to die.',
    symptoms: ['Sudden numbness', 'Confusion', 'Trouble speaking', 'Vision problems', 'Dizziness'],
    causes: ['Blood clots', 'Bleeding in brain', 'High blood pressure', 'Atrial fibrillation', 'Smoking'],
    treatments: ['Clot-busting drugs', 'Blood thinners', 'Surgery', 'Rehabilitation', 'Lifestyle changes'],
  },
  {
    id: '33',
    name: 'Pneumonia',
    category: 'Respiratory',
    overview: 'An infection that inflames air sacs in one or both lungs.',
    symptoms: ['Chest pain', 'Cough', 'Fever', 'Chills', 'Shortness of breath'],
    causes: ['Bacteria', 'Viruses', 'Fungi', 'Chemical irritants', 'Aspiration'],
    treatments: ['Antibiotics', 'Antiviral medications', 'Fever reducers', 'Rest', 'Hospitalization in severe cases'],
  },
  {
    id: '34',
    name: 'Schizophrenia',
    category: 'Mental Health',
    overview: 'A serious disorder affecting how a person thinks, feels, and behaves.',
    symptoms: ['Hallucinations', 'Delusions', 'Disorganized thinking', 'Social withdrawal', 'Lack of motivation'],
    causes: ['Genetics', 'Brain chemistry', 'Environmental factors', 'Prenatal exposure'],
    treatments: ['Antipsychotic medications', 'Psychotherapy', 'Social skills training', 'Hospitalization', 'Community support'],
  },
  {
    id: '35',
    name: 'Glaucoma',
    category: 'Ophthalmological',
    overview: 'A group of eye conditions that damage the optic nerve.',
    symptoms: ['Blind spots', 'Tunnel vision', 'Eye pain', 'Nausea', 'Blurred vision'],
    causes: ['High eye pressure', 'Genetics', 'Age', 'Eye injuries', 'Certain medications'],
    treatments: ['Eye drops', 'Oral medications', 'Laser treatment', 'Surgery', 'Regular monitoring'],
  },
  {
    id: '36',
    name: 'Osteoporosis',
    category: 'Musculoskeletal',
    overview: 'A bone disease that occurs when the body loses too much bone or makes too little bone.',
    symptoms: ['Back pain', 'Loss of height', 'Stooped posture', 'Fractures', 'Reduced mobility'],
    causes: ['Aging', 'Hormonal changes', 'Genetics', 'Nutritional deficiencies', 'Lifestyle factors'],
    treatments: ['Bisphosphonates', 'Calcium supplements', 'Vitamin D', 'Exercise', 'Fall prevention'],
  },
  {
    id: '37',
    name: 'Tuberculosis',
    category: 'Infectious',
    overview: 'A potentially serious infectious disease that mainly affects the lungs.',
    symptoms: ['Persistent cough', 'Chest pain', 'Coughing up blood', 'Fatigue', 'Weight loss'],
    causes: ['Mycobacterium tuberculosis', 'Weakened immune system', 'Close contact with infected person'],
    treatments: ['Antibiotics', 'Directly observed therapy', 'Rest', 'Nutritional support', 'Isolation'],
  },
  {
    id: '38',
    name: 'Pancreatitis',
    category: 'Digestive',
    overview: 'Inflammation of the pancreas, an organ that produces digestive enzymes and hormones.',
    symptoms: ['Upper abdominal pain', 'Abdominal pain radiating to back', 'Nausea', 'Vomiting', 'Fever'],
    causes: ['Gallstones', 'Alcohol consumption', 'High triglycerides', 'Genetic factors', 'Certain medications'],
    treatments: ['Hospitalization', 'IV fluids', 'Pain medications', 'Pancreatic enzyme supplements', 'Lifestyle changes'],
  },
  {
    id: '39',
    name: 'Bipolar Disorder',
    category: 'Mental Health',
    overview: 'A mental health condition causing extreme mood swings with emotional highs and lows.',
    symptoms: ['Manic episodes', 'Depressive episodes', 'Impaired judgment', 'Sleep disturbances', 'Risky behavior'],
    causes: ['Genetics', 'Brain structure', 'Chemical imbalances', 'Environmental factors', 'Trauma'],
    treatments: ['Mood stabilizers', 'Antipsychotics', 'Psychotherapy', 'Lifestyle management', 'Support groups'],
  },
  {
    id: '40',
    name: 'HIV/AIDS',
    category: 'Infectious',
    overview: 'A virus that attacks the immune system, making a person vulnerable to other infections.',
    symptoms: ['Fever', 'Fatigue', 'Swollen lymph nodes', 'Weight loss', 'Opportunistic infections'],
    causes: ['Human Immunodeficiency Virus', 'Unprotected sex', 'Sharing needles', 'Mother-to-child transmission'],
    treatments: ['Antiretroviral therapy', 'Prophylactic medications', 'Lifestyle changes', 'Regular monitoring', 'Supportive care'],
  },
  {
    id: '41',
    name: 'Hepatitis B',
    category: 'Infectious',
    overview: 'A serious liver infection caused by the hepatitis B virus.',
    symptoms: ['Abdominal pain', 'Dark urine', 'Fever', 'Joint pain', 'Jaundice'],
    causes: ['Hepatitis B virus', 'Contact with infected blood', 'Sexual contact', 'Mother-to-child transmission'],
    treatments: ['Antiviral medications', 'Interferon injections', 'Liver transplant', 'Vaccination', 'Lifestyle changes'],
  },
  {
    id: '42',
    name: 'Hyperthyroidism',
    category: 'Endocrine',
    overview: 'Overproduction of thyroid hormones by the thyroid gland.',
    symptoms: ['Weight loss', 'Rapid heartbeat', 'Anxiety', 'Tremor', 'Increased appetite'],
    causes: ['Graves\' disease', 'Thyroid nodules', 'Thyroiditis', 'Excess iodine', 'Medications'],
    treatments: ['Anti-thyroid medications', 'Radioactive iodine', 'Beta blockers', 'Surgery', 'Thyroidectomy'],
  },
  {
    id: '43',
    name: 'Polycystic Ovary Syndrome',
    category: 'Endocrine',
    overview: 'A hormonal disorder common among women of reproductive age.',
    symptoms: ['Irregular periods', 'Excess hair growth', 'Acne', 'Weight gain', 'Infertility'],
    causes: ['Insulin resistance', 'Hormonal imbalance', 'Genetics', 'Low-grade inflammation'],
    treatments: ['Birth control pills', 'Metformin', 'Lifestyle changes', 'Fertility treatments', 'Hair removal methods'],
  },
  {
    id: '44',
    name: 'Scoliosis',
    category: 'Musculoskeletal',
    overview: 'A sideways curvature of the spine that occurs most often during the growth spurt before puberty.',
    symptoms: ['Uneven shoulders', 'Uneven waist', 'One hip higher than other', 'Back pain', 'Breathing problems'],
    causes: ['Genetics', 'Neuromuscular conditions', 'Birth defects', 'Injuries', 'Unknown in most cases'],
    treatments: ['Observation', 'Bracing', 'Physical therapy', 'Surgery', 'Chiropractic care'],
  },
  {
    id: '45',
    name: 'Gallstones',
    category: 'Digestive',
    overview: 'Hardened deposits of digestive fluid that form in the gallbladder.',
    symptoms: ['Sudden intense pain', 'Back pain', 'Nausea', 'Vomiting', 'Indigestion'],
    causes: ['Excess cholesterol', 'Excess bilirubin', 'Gallbladder dysfunction', 'Obesity', 'Pregnancy'],
    treatments: ['Gallbladder removal', 'Medications to dissolve stones', 'Lifestyle changes', 'Dietary modifications'],
  },
  {
    id: '46',
    name: 'Diverticulitis',
    category: 'Digestive',
    overview: 'Inflammation or infection of small pouches that form in the digestive tract.',
    symptoms: ['Abdominal pain', 'Fever', 'Nausea', 'Changes in bowel habits', 'Bloating'],
    causes: ['Diverticula formation', 'Obstruction', 'Increased pressure in colon', 'Low-fiber diet', 'Aging'],
    treatments: ['Antibiotics', 'Liquid diet', 'Pain relievers', 'Surgery in severe cases', 'High-fiber diet'],
  },
  {
    id: '47',
    name: 'Shingles',
    category: 'Infectious',
    overview: 'A viral infection causing a painful rash, caused by the varicella-zoster virus.',
    symptoms: ['Painful rash', 'Blisters', 'Burning sensation', 'Fever', 'Headache'],
    causes: ['Reactivation of chickenpox virus', 'Weakened immune system', 'Age', 'Stress'],
    treatments: ['Antiviral medications', 'Pain relievers', 'Topical creams', 'Vaccination', 'Cool compresses'],
  },
  {
    id: '48',
    name: 'Acid Reflux',
    category: 'Digestive',
    overview: 'A condition where stomach acid flows back into the esophagus.',
    symptoms: ['Heartburn', 'Regurgitation', 'Chest pain', 'Difficulty swallowing', 'Chronic cough'],
    causes: ['Weak esophageal sphincter', 'Obesity', 'Pregnancy', 'Hiatal hernia', 'Certain foods'],
    treatments: ['Antacids', 'H2 blockers', 'Proton pump inhibitors', 'Lifestyle changes', 'Weight loss'],
  },
  {
    id: '49',
    name: 'Conjunctivitis',
    category: 'Ophthalmological',
    overview: 'Inflammation of the transparent membrane that lines the eyelid and eyeball.',
    symptoms: ['Redness', 'Itchiness', 'Discharge', 'Tearing', 'Crusty eyelids'],
    causes: ['Viruses', 'Bacteria', 'Allergies', 'Chemical irritants', 'Foreign objects'],
    treatments: ['Artificial tears', 'Antibiotic eye drops', 'Antihistamines', 'Cold compresses', 'Proper hygiene'],
  },
  {
    id: '50',
    name: 'Bronchitis',
    category: 'Respiratory',
    overview: 'Inflammation of the lining of bronchial tubes, which carry air to and from the lungs.',
    symptoms: ['Cough', 'Mucus production', 'Fatigue', 'Shortness of breath', 'Mild fever'],
    causes: ['Viruses', 'Bacteria', 'Smoking', 'Air pollution', 'Dust'],
    treatments: ['Rest', 'Fluids', 'Cough medicine', 'Humidifier', 'Avoiding irritants'],
  },
  {
    id: '51',
    name: 'Kidney Stones',
    category: 'Renal',
    overview: 'Hard deposits made of minerals and salts that form inside the kidneys.',
    symptoms: ['Severe pain', 'Pain during urination', 'Pink/red urine', 'Nausea', 'Fever'],
    causes: ['Dehydration', 'Diet', 'Obesity', 'Medical conditions', 'Supplements'],
    treatments: ['Pain relievers', 'Medical therapy', 'Hydration', 'Sound wave therapy', 'Surgery'],
  },
  {
    id: '52',
    name: 'Meniere\'s Disease',
    category: 'Neurological',
    overview: 'An inner ear disorder causing episodes of vertigo and hearing loss.',
    symptoms: ['Vertigo', 'Hearing loss', 'Tinnitus', 'Fullness in ear', 'Balance problems'],
    causes: ['Fluid buildup in inner ear', 'Autoimmune reaction', 'Genetics', 'Allergies', 'Migraine association'],
    treatments: ['Medications', 'Diuretics', 'Rehabilitation', 'Hearing aids', 'Surgery'],
  },
  {
    id: '53',
    name: 'Rosacea',
    category: 'Dermatological',
    overview: 'A common skin condition that causes redness and visible blood vessels in the face.',
    symptoms: ['Facial redness', 'Swollen red bumps', 'Eye problems', 'Enlarged nose', 'Visible blood vessels'],
    causes: ['Genetics', 'Environmental factors', 'Blood vessel issues', 'Mites', 'Bacteria'],
    treatments: ['Topical medications', 'Oral antibiotics', 'Laser therapy', 'Lifestyle changes', 'Sun protection'],
  },
  {
    id: '54',
    name: 'Hemorrhoids',
    category: 'Digestive',
    overview: 'Swollen veins in the lowest part of rectum and anus.',
    symptoms: ['Pain', 'Itching', 'Bleeding', 'Lump near anus', 'Discomfort'],
    causes: ['Straining during bowel movements', 'Chronic diarrhea', 'Pregnancy', 'Obesity', 'Low fiber diet'],
    treatments: ['Topical treatments', 'Fiber supplements', 'Sitz baths', 'Minimally invasive procedures', 'Surgery'],
  },
  {
    id: '55',
    name: 'Impetigo',
    category: 'Dermatological',
    overview: 'A common and highly contagious skin infection that mainly affects infants and children.',
    symptoms: ['Red sores', 'Blisters', 'Honey-colored crusts', 'Itching', 'Swollen lymph nodes'],
    causes: ['Bacteria (Staphylococcus or Streptococcus)', 'Skin breaks', 'Warm weather', 'Crowded conditions'],
    treatments: ['Antibiotic ointments', 'Oral antibiotics', 'Proper hygiene', 'Isolation', 'Keeping skin clean'],
  },
  {
    id: '56',
    name: 'Sinusitis',
    category: 'Respiratory',
    overview: 'Inflammation or swelling of the tissue lining the sinuses.',
    symptoms: ['Nasal congestion', 'Thick nasal discharge', 'Facial pain', 'Headache', 'Reduced sense of smell'],
    causes: ['Viral infections', 'Bacterial infections', 'Allergies', 'Nasal polyps', 'Deviated septum'],
    treatments: ['Nasal sprays', 'Decongestants', 'Antibiotics', 'Pain relievers', 'Saline irrigation'],
  },
  {
    id: '57',
    name: 'Cystic Fibrosis',
    category: 'Genetic',
    overview: 'A genetic disorder that affects mostly the lungs but also the pancreas, liver, and intestine.',
    symptoms: ['Persistent cough', 'Frequent lung infections', 'Wheezing', 'Poor growth', 'Salty-tasting skin'],
    causes: ['Inherited CFTR gene mutations', 'Autosomal recessive inheritance'],
    treatments: ['Airway clearance techniques', 'Inhaled medicines', 'Pancreatic enzyme supplements', 'Antibiotics', 'CFTR modulators'],
  },
  {
    id: '58',
    name: 'Tinnitus',
    category: 'Neurological',
    overview: 'The perception of noise or ringing in the ears when no external sound is present.',
    symptoms: ['Ringing in ears', 'Buzzing', 'Hissing', 'Clicking', 'Roaring'],
    causes: ['Hearing loss', 'Ear injury', 'Circulatory system disorders', 'Age', 'Loud noise exposure'],
    treatments: ['Hearing aids', 'Sound-masking devices', 'Medication adjustments', 'Cognitive therapy', 'Stress management'],
  },
  {
    id: '59',
    name: 'Ulcerative Colitis',
    category: 'Digestive',
    overview: 'An inflammatory bowel disease causing inflammation and ulcers in the digestive tract.',
    symptoms: ['Diarrhea', 'Abdominal pain', 'Rectal bleeding', 'Urgency to defecate', 'Weight loss'],
    causes: ['Immune system malfunction', 'Genetics', 'Environment', 'Gut bacteria imbalance'],
    treatments: ['Anti-inflammatory drugs', 'Immune system suppressors', 'Biologics', 'Surgery', 'Dietary changes'],
  },
  {
    id: '60',
    name: 'Sepsis',
    category: 'Infectious',
    overview: "A life-threatening condition that occurs when the body's response to infection damages its own tissues.",
    symptoms: ['Fever', 'Increased heart rate', 'Confusion', 'Difficulty breathing', 'Extreme pain'],
    causes: ['Bacterial infections', 'Viral infections', 'Fungal infections', 'Weakened immune system'],
    treatments: ['Antibiotics', 'IV fluids', 'Vasopressors', 'Corticosteroids', 'Supportive care'],
  },
  {
    id: '61',
    name: 'Macular Degeneration',
    category: 'Ophthalmological',
    overview: 'An eye disease that may result in blurred or no vision in the center of the visual field.',
    symptoms: ['Blurred vision', 'Dark spots', 'Distorted vision', 'Difficulty recognizing faces', 'Reduced central vision'],
    causes: ['Aging', 'Genetics', 'Smoking', 'Obesity', 'Cardiovascular disease'],
    treatments: ['Anti-angiogenic drugs', 'Photodynamic therapy', 'Laser therapy', 'Vitamins', 'Low vision aids'],
  },
  {
    id: '62',
    name: 'Pulmonary Embolism',
    category: 'Cardiovascular',
    overview: 'A blockage in one of the pulmonary arteries in the lungs.',
    symptoms: ['Shortness of breath', 'Chest pain', 'Cough', 'Rapid heartbeat', 'Leg pain or swelling'],
    causes: ['Deep vein thrombosis', 'Blood clots', 'Surgery', 'Prolonged immobility', 'Cancer'],
    treatments: ['Anticoagulants', 'Thrombolytics', 'Vena cava filter', 'Surgery', 'Compression stockings'],
  },
  {
    id: '63',
    name: 'Appendicitis',
    category: 'Digestive',
    overview: 'Inflammation of the appendix, a finger-shaped pouch that projects from the colon.',
    symptoms: ['Abdominal pain', 'Nausea', 'Vomiting', 'Loss of appetite', 'Fever'],
    causes: ['Blockage in appendix', 'Infection', 'Inflammation', 'Trauma', 'Genetics'],
    treatments: ['Surgery (appendectomy)', 'Antibiotics', 'Pain medication', 'IV fluids', 'Rest'],
  },
  {
    id: '64',
    name: 'Bursitis',
    category: 'Musculoskeletal',
    overview: 'Painful inflammation of bursae, the fluid-filled sacs that cushion the bones, tendons and muscles near joints.',
    symptoms: ['Joint pain', 'Stiffness', 'Swelling', 'Redness', 'Limited movement'],
    causes: ['Repetitive motions', 'Prolonged pressure', 'Injury', 'Infection', 'Inflammatory conditions'],
    treatments: ['Rest', 'Ice therapy', 'Medications', 'Physical therapy', 'Corticosteroid injections'],
  },
  {
    id: '65',
    name: 'Cellulitis',
    category: 'Dermatological',
    overview: 'A common bacterial skin infection that causes redness, swelling, and pain in the infected area.',
    symptoms: ['Red area of skin', 'Swelling', 'Tenderness', 'Warmth', 'Fever'],
    causes: ['Bacterial infection', 'Skin breaks', 'Weakened immune system', 'Skin conditions', 'Lymphedema'],
    treatments: ['Antibiotics', 'Pain relievers', 'Elevation', 'Cool compresses', 'Rest'],
  },
  {
    id: '66',
    name: 'Cluster Headaches',
    category: 'Neurological',
    overview: 'Extremely painful headaches that occur in clusters or cyclical patterns.',
    symptoms: ['Severe pain', 'Pain around one eye', 'Restlessness', 'Eye redness', 'Stuffy nose'],
    causes: ['Hypothalamus dysfunction', 'Genetics', 'Circadian rhythm', 'Serotonin levels', 'Histamine release'],
    treatments: ['Oxygen therapy', 'Triptans', 'Preventive medications', 'Nerve stimulation', 'Lifestyle changes'],
  },
  {
    id: '67',
    name: 'Dementia',
    category: 'Neurological',
    overview: 'A group of thinking and social symptoms that interfere with daily functioning.',
    symptoms: ['Memory loss', 'Communication problems', 'Difficulty with complex tasks', 'Personality changes', 'Confusion'],
    causes: ['Alzheimer\'s disease', 'Vascular issues', 'Lewy body dementia', 'Frontotemporal dementia', 'Head injuries'],
    treatments: ['Medications', 'Cognitive stimulation', 'Occupational therapy', 'Environment modification', 'Support groups'],
  },
  {
    id: '68',
    name: 'Epstein-Barr Virus',
    category: 'Infectious',
    overview: 'A virus in the herpes family that causes infectious mononucleosis.',
    symptoms: ['Fatigue', 'Fever', 'Sore throat', 'Swollen lymph nodes', 'Enlarged spleen'],
    causes: ['Human herpesvirus 4', 'Saliva transmission', 'Blood transfusions', 'Organ transplants'],
    treatments: ['Rest', 'Hydration', 'Pain relievers', 'Corticosteroids', 'Avoiding contact sports'],
  },
  {
    id: '69',
    name: 'Gestational Diabetes',
    category: 'Endocrine',
    overview: 'A type of diabetes that appears during pregnancy in women who didn\'t have diabetes before.',
    symptoms: ['Increased thirst', 'Frequent urination', 'Fatigue', 'Blurred vision', 'Yeast infections'],
    causes: ['Hormonal changes', 'Insulin resistance', 'Genetics', 'Obesity', 'Previous history'],
    treatments: ['Dietary changes', 'Exercise', 'Blood sugar monitoring', 'Medication', 'Regular prenatal care'],
  },
  {
    id: '70',
    name: 'Herniated Disc',
    category: 'Musculoskeletal',
    overview: 'A problem with one of the rubbery cushions (discs) between the vertebrae.',
    symptoms: ['Back pain', 'Leg pain', 'Arm pain', 'Numbness', 'Weakness'],
    causes: ['Disc degeneration', 'Injury', 'Strain', 'Genetics', 'Excess weight'],
    treatments: ['Physical therapy', 'Medications', 'Injections', 'Surgery', 'Lifestyle changes'],
  },
  {
    id: '71',
    name: 'Influenza',
    category: 'Infectious',
    overview: 'A viral infection that attacks the respiratory system.',
    symptoms: ['Fever', 'Aches', 'Cough', 'Sore throat', 'Fatigue'],
    causes: ['Influenza viruses', 'Airborne droplets', 'Contaminated surfaces'],
    treatments: ['Rest', 'Fluids', 'Antiviral medications', 'Pain relievers', 'Annual vaccination'],
  },
  {
    id: '72',
    name: 'Interstitial Cystitis',
    category: 'Urological',
    overview: 'A chronic condition causing bladder pressure, bladder pain and sometimes pelvic pain.',
    symptoms: ['Bladder pain', 'Urgency', 'Frequency', 'Pain during intercourse', 'Pelvic pain'],
    causes: ['Bladder lining defect', 'Autoimmune reaction', 'Infection', 'Genetics', 'Allergic reaction'],
    treatments: ['Physical therapy', 'Medications', 'Bladder instillation', 'Nerve stimulation', 'Surgery'],
  },
  {
    id: '73',
    name: 'Laryngitis',
    category: 'Respiratory',
    overview: 'Inflammation of the voice box (larynx) from overuse, irritation or infection.',
    symptoms: ['Hoarseness', 'Voice loss', 'Sore throat', 'Dry throat', 'Dry cough'],
    causes: ['Viral infections', 'Vocal strain', 'Bacterial infections', 'Acid reflux', 'Smoking'],
    treatments: ['Voice rest', 'Hydration', 'Humidifier', 'Avoiding irritants', 'Medications'],
  },
  {
    id: '74',
    name: 'Lyme Disease',
    category: 'Infectious',
    overview: 'An infectious disease caused by Borrelia bacteria, spread by ticks.',
    symptoms: ['Rash', 'Fever', 'Headache', 'Fatigue', 'Joint pain'],
    causes: ['Borrelia burgdorferi', 'Tick bites', 'Outdoor activities', 'Forest areas'],
    treatments: ['Antibiotics', 'Pain relievers', 'Intravenous antibiotics', 'Lifestyle modifications'],
  },
  {
    id: '75',
    name: 'Meningitis',
    category: 'Infectious',
    overview: 'Inflammation of the membranes surrounding the brain and spinal cord.',
    symptoms: ['Headache', 'Fever', 'Stiff neck', 'Sensitivity to light', 'Confusion'],
    causes: ['Viral infections', 'Bacterial infections', 'Fungal infections', 'Parasitic infections'],
    treatments: ['Antibiotics', 'Corticosteroids', 'Antiviral medications', 'Supportive care', 'Vaccination'],
  },
  {
    id: '76',
    name: 'Myasthenia Gravis',
    category: 'Autoimmune',
    overview: 'A chronic autoimmune neuromuscular disease causing weakness in the skeletal muscles.',
    symptoms: ['Muscle weakness', 'Drooping eyelids', 'Double vision', 'Difficulty swallowing', 'Fatigue'],
    causes: ['Autoimmune attack', 'Thymus gland problems', 'Genetics', 'Antibodies'],
    treatments: ['Medications', 'Thymectomy', 'Plasmapheresis', 'Intravenous therapy', 'Lifestyle changes'],
  },
  {
    id: '77',
    name: 'Narcolepsy',
    category: 'Sleep Disorder',
    overview: 'A chronic sleep disorder characterized by overwhelming daytime drowsiness and sudden attacks of sleep.',
    symptoms: ['Excessive daytime sleepiness', 'Sudden loss of muscle tone', 'Sleep paralysis', 'Hallucinations', 'Disrupted sleep'],
    causes: ['Genetics', 'Autoimmune response', 'Brain injuries', 'Infections', 'Environmental factors'],
    treatments: ['Stimulants', 'SSRIs', 'Sodium oxybate', 'Lifestyle changes', 'Scheduled naps'],
  },
  {
    id: '78',
    name: 'Peripheral Neuropathy',
    category: 'Neurological',
    overview: 'Damage to peripheral nerves causing weakness, numbness and pain in hands and feet.',
    symptoms: ['Numbness', 'Tingling', 'Sharp pain', 'Sensitivity', 'Muscle weakness'],
    causes: ['Diabetes', 'Injuries', 'Infections', 'Toxins', 'Genetic disorders'],
    treatments: ['Pain relievers', 'Anti-seizure medications', 'Topical treatments', 'Physical therapy', 'Transcutaneous electrical nerve stimulation'],
  },
  {
    id: '79',
    name: 'Peyronie\'s Disease',
    category: 'Urological',
    overview: 'Development of fibrous scar tissue inside the penis causing curved, painful erections.',
    symptoms: ['Scar tissue', 'Bent penis', 'Pain', 'Erection problems', 'Shortening of penis'],
    causes: ['Injury', 'Genetics', 'Autoimmune factors', 'Age', 'Connective tissue disorders'],
    treatments: ['Medications', 'Injections', 'Surgery', 'Traction therapy', 'Radiation therapy'],
  },
  {
    id: '80',
    name: 'Prostatitis',
    category: 'Urological',
    overview: 'Inflammation of the prostate gland.',
    symptoms: ['Pain', 'Urinary problems', 'Sexual dysfunction', 'Flu-like symptoms', 'Pelvic pain'],
    causes: ['Bacterial infection', 'Nerve damage', 'Immune system response', 'Psychological stress', 'Injury'],
    treatments: ['Antibiotics', 'Alpha blockers', 'Anti-inflammatory medications', 'Pain relievers', 'Lifestyle changes'],
  },
  {
    id: '81',
    name: 'Restless Legs Syndrome',
    category: 'Neurological',
    overview: 'A condition characterized by an uncontrollable urge to move the legs.',
    symptoms: ['Leg discomfort', 'Urge to move', 'Worsening at rest', 'Relief with movement', 'Evening symptoms'],
    causes: ['Genetics', 'Iron deficiency', 'Kidney failure', 'Pregnancy', 'Nerve damage'],
    treatments: ['Iron supplements', 'Medications', 'Lifestyle changes', 'Massage', 'Hot/cold therapy'],
  },
  {
    id: '82',
    name: 'Scabies',
    category: 'Dermatological',
    overview: 'An itchy skin condition caused by a tiny burrowing mite called Sarcoptes scabiei.',
    symptoms: ['Intense itching', 'Burrow tracks', 'Blisters', 'Sores', 'Rash'],
    causes: ['Sarcoptes scabiei mites', 'Close physical contact', 'Sharing bedding', 'Crowded living conditions'],
    treatments: ['Topical medications', 'Oral medications', 'Antihistamines', 'Cleaning household items', 'Avoiding scratching'],
  },
  {
    id: '83',
    name: 'Spina Bifida',
    category: 'Neurological',
    overview: 'A birth defect that occurs when the spine and spinal cord don\'t form properly.',
    symptoms: ['Fluid-filled sac on back', 'Bowel problems', 'Bladder issues', 'Leg weakness', 'Hydrocephalus'],
    causes: ['Genetics', 'Folic acid deficiency', 'Environmental factors', 'Obesity', 'Uncontrolled diabetes'],
    treatments: ['Surgery', 'Physical therapy', 'Assistive devices', 'Medications', 'Lifestyle modifications'],
  },
  {
    id: '84',
    name: 'Temporal Arteritis',
    category: 'Autoimmune',
    overview: 'Inflammation of the lining of the arteries, most commonly in the temples.',
    symptoms: ['Headache', 'Jaw pain', 'Vision problems', 'Scalp tenderness', 'Fever'],
    causes: ['Immune system response', 'Genetics', 'Age', 'Environmental factors', 'Infections'],
    treatments: ['High-dose corticosteroids', 'Aspirin', 'Calcium supplements', 'Regular monitoring', 'Vision care'],
  },
  {
    id: '85',
    name: 'Tourette Syndrome',
    category: 'Neurological',
    overview: 'A disorder involving repetitive movements or unwanted sounds (tics).',
    symptoms: ['Motor tics', 'Vocal tics', 'Eye blinking', 'Shoulder shrugging', 'Vocal outbursts'],
    causes: ['Genetics', 'Brain structure', 'Neurotransmitters', 'Environmental factors', 'Infections'],
    treatments: ['Behavioral therapy', 'Medications', 'Deep brain stimulation', 'Support groups', 'Education'],
  },
  {
    id: '86',
    name: 'Ulcers',
    category: 'Digestive',
    overview: 'Open sores that develop on the inside lining of the stomach and upper portion of the small intestine.',
    symptoms: ['Burning pain', 'Bloating', 'Heartburn', 'Nausea', 'Dark stools'],
    causes: ['H. pylori infection', 'NSAIDs', 'Smoking', 'Alcohol', 'Stress'],
    treatments: ['Antibiotics', 'Acid reducers', 'Protective medications', 'Lifestyle changes', 'Avoiding irritants'],
  },
  {
    id: '87',
    name: 'Varicose Veins',
    category: 'Cardiovascular',
    overview: 'Enlarged, swollen, and twisting veins, often appearing blue or dark purple.',
    symptoms: ['Visible twisted veins', 'Aching pain', 'Swelling', 'Heaviness', 'Skin discoloration'],
    causes: ['Weak valves', 'Age', 'Pregnancy', 'Obesity', 'Standing for long periods'],
    treatments: ['Compression stockings', 'Sclerotherapy', 'Laser treatment', 'Vein stripping', 'Lifestyle changes'],
  },
  {
    id: '88',
    name: 'Vitiligo',
    category: 'Dermatological',
    overview: 'A disease that causes loss of skin color in blotches.',
    symptoms: ['Patchy loss of skin color', 'Premature whitening of hair', 'Loss of color in mouth', 'Eye color changes'],
    causes: ['Autoimmune condition', 'Genetics', 'Triggers', 'Oxidative stress', 'Viral causes'],
    treatments: ['Topical medications', 'Light therapy', 'Depigmentation', 'Surgery', 'Cosmetic options'],
  },
  {
    id: '89',
    name: 'West Nile Virus',
    category: 'Infectious',
    overview: 'A virus transmitted by mosquitoes that can cause neurological disease.',
    symptoms: ['Fever', 'Headache', 'Body aches', 'Skin rash', 'Swollen lymph glands'],
    causes: ['West Nile virus', 'Mosquito bites', 'Bird reservoirs', 'Outdoor exposure'],
    treatments: ['Supportive care', 'Pain relievers', 'Hospitalization for severe cases', 'Prevention'],
  },
  {
    id: '90',
    name: 'Wilson\'s Disease',
    category: 'Genetic',
    overview: 'A rare inherited disorder that causes copper to accumulate in the liver, brain and other vital organs.',
    symptoms: ['Fatigue', 'Jaundice', 'Abdominal pain', 'Tremors', 'Difficulty walking'],
    causes: ['ATP7B gene mutation', 'Copper accumulation', 'Inherited from parents'],
    treatments: ['Chelating agents', 'Zinc supplements', 'Dietary changes', 'Liver transplant', 'Regular monitoring'],
  },
  {
    id: '91',
    name: 'Zika Virus',
    category: 'Infectious',
    overview: 'A mosquito-borne flavivirus that can cause birth defects.',
    symptoms: ['Fever', 'Rash', 'Joint pain', 'Conjunctivitis', 'Headache'],
    causes: ['Zika virus', 'Mosquito bites', 'Sexual transmission', 'Mother to child'],
    treatments: ['Rest', 'Hydration', 'Pain relievers', 'Avoiding mosquito bites', 'Pregnancy precautions'],
  },
  {
    id: '92',
    name: 'Adrenal Insufficiency',
    category: 'Endocrine',
    overview: 'A disorder that occurs when the adrenal glands don\'t produce enough hormones.',
    symptoms: ['Fatigue', 'Weight loss', 'Low blood pressure', 'Hyperpigmentation', 'Salt craving'],
    causes: ['Autoimmune disease', 'Infections', 'Cancer', 'Bleeding', 'Genetic defects'],
    treatments: ['Hormone replacement', 'Corticosteroids', 'Mineralocorticoids', 'Emergency injections', 'Medical alert bracelet'],
  },
  {
    id: '93',
    name: 'Alopecia Areata',
    category: 'Autoimmune',
    overview: 'An autoimmune condition causing patchy hair loss.',
    symptoms: ['Patchy hair loss', 'Bald spots', 'Hair loss on scalp', 'Nail changes', 'Itching'],
    causes: ['Autoimmune reaction', 'Genetics', 'Environmental triggers', 'Stress'],
    treatments: ['Corticosteroids', 'Minoxidil', 'Anthralin', 'Immunotherapy', 'Hair transplant'],
  },
  {
    id: '94',
    name: 'Amyotrophic Lateral Sclerosis',
    category: 'Neurological',
    overview: 'A progressive neurodegenerative disease affecting nerve cells in the brain and spinal cord.',
    symptoms: ['Muscle weakness', 'Slurred speech', 'Difficulty swallowing', 'Muscle cramps', 'Breathing problems'],
    causes: ['Genetic mutations', 'Chemical imbalance', 'Disorganized immune response', 'Protein mishandling'],
    treatments: ['Riluzole', 'Edaravone', 'Physical therapy', 'Breathing support', 'Nutritional support'],
  },
  {
    id: '95',
    name: 'Ankylosing Spondylitis',
    category: 'Autoimmune',
    overview: 'An inflammatory arthritis affecting the spine and large joints.',
    symptoms: ['Back pain', 'Stiffness', 'Reduced flexibility', 'Hunched posture', 'Fatigue'],
    causes: ['Genetics', 'HLA-B27 gene', 'Environmental factors', 'Infections'],
    treatments: ['NSAIDs', 'Physical therapy', 'Biologics', 'Exercise', 'Posture training'],
  },
  {
    id: '96',
    name: 'Bacterial Vaginosis',
    category: 'Infectious',
    overview: 'A type of vaginal inflammation caused by the overgrowth of bacteria naturally found in the vagina.',
    symptoms: ['Thin discharge', 'Fishy odor', 'Vaginal itching', 'Burning during urination'],
    causes: ['Bacterial imbalance', 'Multiple sexual partners', 'Douching', 'Lack of lactobacilli'],
    treatments: ['Antibiotics', 'Probiotics', 'Proper hygiene', 'Avoiding irritants'],
  },
  {
    id: '97',
    name: 'Barrett\'s Esophagus',
    category: 'Digestive',
    overview: 'A condition in which the flat pink lining of the esophagus is damaged by acid reflux.',
    symptoms: ['Heartburn', 'Chest pain', 'Difficulty swallowing', 'Regurgitation'],
    causes: ['Chronic GERD', 'Obesity', 'Smoking', 'Family history'],
    treatments: ['GERD medications', 'Surveillance endoscopy', 'Surgery', 'Lifestyle changes'],
  },
  {
    id: '98',
    name: 'Benign Prostatic Hyperplasia',
    category: 'Urological',
    overview: 'Enlargement of the prostate gland that can cause urinary problems.',
    symptoms: ['Frequent urination', 'Urgency', 'Weak stream', 'Incomplete emptying', 'Dribbling'],
    causes: ['Aging', 'Hormonal changes', 'Family history', 'Obesity', 'Diabetes'],
    treatments: ['Medications', 'Minimally invasive therapies', 'Surgery', 'Lifestyle changes'],
  },
  {
    id: '99',
    name: 'Blepharitis',
    category: 'Ophthalmological',
    overview: 'Inflammation of the eyelids, usually where eyelashes grow.',
    symptoms: ['Red eyes', 'Swollen eyelids', 'Itching', 'Watery eyes', 'Crusty eyelashes'],
    causes: ['Bacterial infection', 'Skin conditions', 'Blocked oil glands', 'Demodex mites'],
    treatments: ['Eyelid hygiene', 'Warm compresses', 'Antibiotics', 'Steroid eye drops', 'Artificial tears'],
  },
  {
    id: '100',
    name: 'Bruxism',
    category: 'Dental',
    overview: 'A condition in which you grind, gnash or clench your teeth.',
    symptoms: ['Teeth grinding', 'Jaw pain', 'Headaches', 'Tooth damage', 'Sleep disruption'],
    causes: ['Stress', 'Anxiety', 'Sleep disorders', 'Medications', 'Genetics'],
    treatments: ['Mouth guards', 'Stress management', 'Dental correction', 'Medications', 'Behavioral therapy'],
  }

];

